# Generated by Django 6.0.4 on 2026-04-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "edition_type",
                    models.CharField(
                        choices=[
                            ("general", "General Tech"),
                            ("ai_only", "AI Only"),
                            ("startups", "Startups & VC"),
                            ("policy", "Policy & Reg."),
                            ("europe", "Europe Focus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("article_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "newsletter_editions",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=500)),
                ("reliability_score", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=100, unique=True)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("topic", "Topic"),
                            ("geography", "Geography"),
                            ("article_type", "Article Type"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("usage_count", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["tag_type", "tag_name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("url", models.CharField(max_length=255, unique=True)),
                (
                    "tagging_method",
                    models.CharField(
                        choices=[("llm", "LLM"), ("rules", "Rules"), ("none", "None")],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("importance_score", models.FloatField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="newsletter.source",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
                "ordering": ["-ingested_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField()),
                (
                    "assigned_by",
                    models.CharField(
                        choices=[("llm", "LLM"), ("rules", "Rules")], max_length=10
                    ),
                ),
                ("tagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_tags",
                        to="newsletter.article",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_tags",
                        to="newsletter.tag",
                    ),
                ),
            ],
            options={
                "db_table": "article_tags",
            },
        ),
        migrations.CreateModel(
            name="TagRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200)),
                (
                    "match_field",
                    models.CharField(
                        choices=[("title", "Title"), ("content", "Content")],
                        max_length=10,
                    ),
                ),
                ("priority", models.IntegerField(default=1)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="newsletter.tag",
                    ),
                ),
            ],
            options={
                "db_table": "tag_rules",
                "ordering": ["-priority", "keyword"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("section_summary", models.TextField(blank=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_articles",
                        to="newsletter.article",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_articles",
                        to="newsletter.newsletteredition",
                    ),
                ),
            ],
            options={
                "db_table": "newsletter_articles",
                "ordering": ["position"],
                "unique_together": {("newsletter", "article")},
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["published_at"], name="articles_publish_73ad5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["source"], name="articles_source__bca100_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["tagging_method"], name="articles_tagging_267d93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articletag",
            index=models.Index(fields=["tag"], name="article_tag_tag_id_868b34_idx"),
        ),
        migrations.AddIndex(
            model_name="articletag",
            index=models.Index(
                fields=["article"], name="article_tag_article_30f1a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articletag",
            index=models.Index(
                fields=["assigned_by"], name="article_tag_assigne_0ac716_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articletag",
            unique_together={("article", "tag")},
        ),
    ]
